---
apiVersion: v1
kind: Namespace
metadata:
  name: desarrollo
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: desarrollo-cpu-mem
  namespace: desarrollo
spec:
  limits:
  - default:
      cpu: 1
      memory: "200Mi"
    defaultRequest:
      cpu: 0.5
      memory: "100Mi"
    type: Container