apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - name: container-test
    image: polinux/stress
    resources:
      limits:
        cpu: "100m"
        memory: "200Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "50M", --vm-hang", "1"]