---
apiVersion: v1
kind: Namespace
metadata:
  name: desarrollo
  labels:
    name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: desarrollo-cpu-mem
  namespace: desarrollo
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: "200Mi"
    limits.cpu: "2"
    limits.memory: "200Mi"