apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: pod-test
spec:
  containers:
  - name: liveness-test
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: tcp-test
spec:
  containers:
  - name: tcp-test
    image: gcr.io/google_containers/goproxy:0.1
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: http-test
spec:
  containers:
  - name: http-test
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 5
      periodSeconds: 5