apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: nginx:alpine
      name: test-container
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs-volume
  volumes:
    - name: logs-volume
      emptyDir: {}