apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
spec:
  storageClassName: local-path # Se consigue dejandose en blanco o con kubectl get sc
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
