apiVersion: v1
kind: ConfigMap
metadata:
  name: config-maps-nginx
  labels:
    app: front
data:
  nginx.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-maps-vars
  labels:
    app: front
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo DB host es $DB_HOST y DB user es $DB_USER > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d
        - name: script-volume
          mountPath: /opt
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: config-maps-vars
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: config-maps-vars
              key: db_user
      volumes:
        - name: nginx-volume
          configMap:
            name: config-maps-nginx
            items:
            - key: nginx.conf
              path: default.conf # nombre que va a tener una vez montado
        - name: script-volume
          configMap:
            name: config-maps-vars
            items:
            - key: script
              path: script.sh
