apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
    - name: web
      image: python:3.6-alpine
      command: [sh, -c, 'echo "Hello World contenedor 1" > index.html && python -m http.server 8082']
    - name: web2
      image: python:3.6-alpine
      # va a fallar por tener el mismo puerto, se pueden ver los logs con kubectl logs podtest2 -c web2
      command: [sh, -c, 'echo "Hello World contenedor 2" > index.html && python -m http.server 8082']