apiVersion: v1
kind: Secret
metadata:
  name: secreto
  labels:
    app: front
type: Opaque
stringData:
  username: usuario
  password: password
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: front
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secreto
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secreto
          key: password