apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-label
      # de aca para arriba es replicaset, para abajo es template del pod, busca pods que tengan el label app: pod-label y los replica 5 veces, sino los crea con la especificacion de abajo
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3